version: '3'
services:
    web:
        depends_on:
            - frontend
            - backend
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '3050:80'
    backend:
        build:
            dockerfile: Dockerfile
            context: ./backend
        volumes:
            - ./backend:/app
        ports:
            - '5000:5000'
    frontend:
        stdin_open: true
        build:
            dockerfile: Dockerfile
            context: ./frontend
        ports:
            - '3000:3000'
        volumes:
            - /app/node_modules
            - ./frontend:/app